topology:
  name: dc-1-spine1-leaf1a
  networks:
  - name: b1
  - name: b2
    type: bridge
  - name: b3
    type: bridge
  - name: b5
    type: bridge
  - name: b6
    type: bridge
  - name: b9
    type: bridge
  - name: b10
    type: bridge
  - name: b11
    type: bridge
  - name: b13
    type: bridge
  nodes:
  - name: dc1-spine1
    type: ceos
    memory: 2Gi
    cpu: 1000m
    interfaces:
    - name: eth1
      network: b1
    - name: eth2
      network: b2
    - name: eth3
      network: b5
    - name: eth4
      network: b6
  - name: dc1-leaf1a
    type: ceos
    memory: 2Gi
    cpu: 1000m
    interfaces:
    - name: eth1
      network: b1
    - name: eth2
      network: b3
    - name: eth3
      network: b9
    - name: eth4
      network: b10
    - name: eth5
      network: b13
    - name: eth8
      network: b11
