topology:
  name: dc1-leaf1a
  networks:
  - name: b1
    type: bridge
  - name: b2
    type: bridge
  - name: b3
    type: bridge
  - name: b4
    type: bridge
  - name: b5
    type: bridge
  - name: b8
    type: bridge
  nodes:
  - name: dc1-leaf1a
    type: ceos
    memory: 2Gi
    cpu: 1000m
    interfaces:
    - name: eth1
      network: b1
    - name: eth2
      network: b2
    - name: eth3
      network: b3
    - name: eth4
      network: b4
    - name: eth5
      network: b5
    - name: eth8
      network: b8
